var res = {
    background : "res/background.jpg",
    background2 : "res/background2.JPG",
    milestone: "res/milestone.png",
    idle : "res/idle.png",
    ready_1 : "res/ready_1.png",
    ready_2 : "res/ready_2.png",
    ready_3 : "res/ready_3.png",
    ready_4 : "res/ready_4.png",
    ready_5 : "res/ready_5.png",
    strike_1 : "res/strike_1.png",
    strike_2 : "res/strike_2.png",
    strike_3 : "res/strike_3.png",
    strike_4 : "res/strike_4.png",
    strike_5 : "res/strike_5.png",
    strike_f_1 : "res/strike_f_1.png",
    strike_f_2 : "res/strike_f_3.png",
    strike_f_3 : "res/strike_f_3.png",
    strike_f_4 : "res/strike_f_4.png",
    strike_s_1 : "res/strike_s_1.png",
    strike_s_2 : "res/strike_s_2.png",
    strike_s_3 : "res/strike_s_3.png",
    strike_s_4 : "res/strike_s_4.png",
    strike_s_5 : "res/strike_s_5.png",
    penguin_jump_1 : "res/penguin_jump_1.png",
    penguin_jump_2 : "res/penguin_jump_2.png",
    penguin_jump_3 : "res/penguin_jump_3.png",
    penguin_jump_4 : "res/penguin_jump_4.png",
    penguin_jump_5 : "res/penguin_jump_5.png",
    penguin_jump_6 : "res/penguin_jump_6.png",
    penguin_vertical_landing_1 : "res/penguin_vertical_landing_1.png",
    penguin_vertical_landing_2 : "res/penguin_vertical_landing_2.png",
    penguin_vertical_landing_3 : "res/penguin_vertical_landing_3.png",
    penguin_vertical_landing_4 : "res/penguin_vertical_landing_4.png",
    penguin_fly_1 : "res/penguin_fly_1.png",
    penguin_fly_2 : "res/penguin_fly_2.png",
    penguin_fly_3 : "res/penguin_fly_3.png",
    penguin_landing_1 : "res/penguin_landing_1.png",
    penguin_landing_2 : "res/penguin_landing_2.png",
    penguin_landing_3 : "res/penguin_landing_3.png",
    penguin_landing_4 : "res/penguin_landing_4.png",
    button_bottom_pressed_2 : "res/button_bottom_pressed_2.png",
    penguin_nick : "res/penguin_nick.png",
    button_bottom_pressed_3: "res/button_bottom_pressed_3.png",
    penguin_step_left_1: "res/penguin_step_left_1.png",
    penguin_step_left_2: "res/penguin_step_left_2.png",
    penguin_step_left_3: "res/penguin_step_left_3.png",
    penguin_step_right_1: "res/penguin_step_right_1.png",
    penguin_step_right_2: "res/penguin_step_right_2.png",
    penguin_step_right_3: "res/penguin_step_right_3.png",

    button_more_game: "res/button_more.png",
    button_retry: "res/button_retry.png",
    penguin_idle: "res/penguin_idle.png"
};

var g_resources = [
    //image
    res.background,
    res.background2,
    res.idle,
    res.ready_1,
    res.ready_2,
    res.ready_3,
    res.ready_4,
    res.ready_5,
    res.strike_1,
    res.strike_2,
    res.strike_3,
    res.strike_4,
    res.strike_5,
    res.strike_f_1,
    res.strike_f_2,
    res.strike_f_3,
    res.strike_f_4,
    res.strike_s_1,
    res.strike_s_2,
    res.strike_s_3,
    res.strike_s_4,
    res.strike_s_5,
    res.penguin_jump_2,
    res.penguin_jump_3,
    res.penguin_jump_4,
    res.penguin_jump_5,
    res.penguin_jump_6,
    res.button_bottom_pressed_3,
    res.button_bottom_pressed_2,
    res.penguin_vertical_landing_1,
    res.penguin_vertical_landing_2,
    res.penguin_vertical_landing_3,
    res.penguin_vertical_landing_4,
    res.penguin_fly_1,
    res.penguin_fly_2,
    res.penguin_fly_3,
    res.penguin_landing_1,
    res.penguin_landing_2,
    res.penguin_landing_3,
    res.penguin_landing_4,
    res.penguin_nick,
    res.milestone,
    res.button_bottom_pressed_3,
    res.button_more_game,
    res.button_retry,
    res.penguin_step_left_1,
    res.penguin_step_left_2,
    res.penguin_step_left_3,
    res.penguin_step_right_1,
    res.penguin_step_right_2,
    res.penguin_step_right_3,
    res.penguin_idle,
    res.penguin_jump_1
];